# Kitty diff viewer config (kitten diff)
# Catppuccin Mocha colors

pygments_style monokai

# Colors
foreground           #cdd6f4
background           #16131E
title_fg             #cdd6f4
title_bg             #1e1e2e
margin_bg            #1e1e2e
margin_fg            #6c7086
removed_bg           #3f1d24
highlight_removed_bg #6f2d35
removed_margin_bg    #6f2d35
added_bg             #1e352d
highlight_added_bg   #2a463d
added_margin_bg      #2a463d
filler_bg            #1e1e2e
hunk_margin_bg       #241F2E
hunk_bg              #241F2E
search_bg            #f9e2af
search_fg            #1e1e2e
select_bg            #45475a
select_fg            #cdd6f4
